const menu = [
  {
    name: "Pringles BBQ",
    price: 2.5,
    Spicy: false,
    glutenFree: false,
    Sour: false,
    Cheese: false,
    Classic: false,
  },
  {
    name: "Pringles Sour Cream & Onion",
    price: 2.5,
    Spicy: false,
    glutenFree: false,
    Sour: true,
    Cheese: false,
    Classic: false,
  },
  {
    name: "Pringles Cheddar Cheese",
    price: 2.5,
    Spicy: false,
    glutenFree: false,
    Sour: false,
    Cheese: true,
    Classic: false,
  },
  {
    name: "Garden Veggie Straws",
    price: 2.5,
    Spicy: false,
    glutenFree: true,
    Sour: false,
    Cheese: false,
    Classic: false,
  },
  {
    name: "UTZ Red Hot Potato Chips",
    price: 2.5,
    Spicy: true,
    glutenFree: true,
    Sour: false,
    Cheese: false,
    Classic: false,
  },
  {
    name: "Pringles BBQ",
    price: 2.5,
    Spicy: false,
    glutenFree: false,
    Sour: false,
    Cheese: false,
    Classic: false,
  },
  {
    name: "Pringles BBQ",
    price: 2.5,
    Spicy: false,
    glutenFree: false,
    Sour: false,
    Cheese: false,
    Classic: false,
  },
  {
    name: "Pringles BBQ",
    price: 2.5,
    Spicy: false,
    glutenFree: false,
    Sour: false,
    Cheese: false,
    Classic: false,
  },
];

export { menu };
