const menu = [
  {
    name: "Pringles Scorchin' BBQ",
    brand: "Pringles",
    price: 2.5,
    Spicy: false,
    glutenFree: false,
    image: 1,
  },
  {
    name: "Pringles Pizza",
    brand: "Pringles",
    price: 2.5,
    Spicy: false,
    glutenFree: false,
    image: 1,
  },
  {
    name: "Pringles Sour Cream & Onion",
    brand: "Pringles",
    price: 2.5,
    Spicy: false,
    glutenFree: false,
    image: 1,
  },
  {
    name: "Pringles Cheddar Cheese",
    brand: "Pringles",
    price: 2.5,
    Spicy: false,
    glutenFree: false,
    image: 1,
  },
  {
    name: "Pringles Buffalo Ranch",
    brand: "Pringles",
    price: 2.5,
    Spicy: false,
    glutenFree: false,
    image: 1,
  },
  {
    name: "Garden Veggie Straws Zesty Ranch",
    brand: "Garden Veggie Straws",
    price: 2.5,
    Spicy: false,
    glutenFree: true,
    image: 1,
  },
  {
    name: "Garden Veggie Straws Sea Salt",
    brand: "Garden Veggie Straws",
    price: 2.5,
    Spicy: false,
    glutenFree: true,
    image: 1,
  },
  {
    name: "Garden Veggie Straws Screamin' Hot",
    brand: "Garden Veggie Straws",
    price: 2.5,
    Spicy: true,
    glutenFree: true,
    image: 1,
  },
  {
    name: "Garden Veggie Straws Cheddar Cheese",
    brand: "Garden Veggie Straws",
    price: 2.5,
    Spicy: true,
    glutenFree: true,
    image: 1,
  },
  {
    name: "UTZ Red Hot Potato Chips",
    brand: "UTZ",
    price: 1.5,
    Spicy: true,
    glutenFree: true,
    image: 1,
  },
  {
    name: "UTZ Salt'n Vinegar",
    brand: "UTZ",
    price: 1.5,
    Spicy: true,
    glutenFree: true,
    image: 1,
  },
  {
    name: "UTZ Original Potato Chips",
    brand: "UTZ",
    price: 1.5,
    Spicy: true,
    glutenFree: true,
    image: 1,
  },
  {
    name: "UTZ Ripples Original Potato Chips",
    brand: "UTZ",
    price: 1.5,
    Spicy: true,
    glutenFree: true,
    image: 1,
  },
  {
    name: "UTZ Honey Barbeque Potato Chips",
    brand: "UTZ",
    price: 1.5,
    Spicy: true,
    glutenFree: true,
    image: 1,
  },
  {
    name: "Takis Zombie",
    brand: "Takis",
    price: 2,
    Spicy: true,
    glutenFree: false,
    image: 1,
  },
  {
    name: "Takis Fuego",
    brand: "Takis",
    price: 2.5,
    Spicy: true,
    glutenFree: false,
    image: 1,
  },
  {
    name: "Takis Blue Heat",
    brand: "Takis",
    price: 2.5,
    Spicy: true,
    glutenFree: false,
    image: 1,
  },
  {
    name: "Takis Dragon Sweet Chili",
    brand: "Takis",
    price: 2.5,
    Spicy: true,
    glutenFree: false,
    image: 1,
  },
  {
    name: "Lay's Classic",
    brand: "Lays's",
    price: 2.5,
    Spicy: false,
    glutenFree: true,
    image: 1,
  },
  {
    name: "Lay's Flamin' Hot",
    brand: "Lays's",
    price: 2.5,
    Spicy: true,
    glutenFree: true,
    image: 1,
  },
  {
    name: "Lay's Barbecue",
    brand: "Lays's",
    price: 2.5,
    Spicy: false,
    glutenFree: true,
    image: 1,
  },
  {
    name: "Lay's Cheddar Bacon Mac & Cheese",
    brand: "Lays's",
    price: 2.5,
    Spicy: false,
    glutenFree: true,
    image: 1,
  },
  {
    name: "Lay's Spanish Tomato Tango",
    brand: "Lays's",
    price: 2.5,
    Spicy: false,
    glutenFree: true,
    image: 1,
  },
  {
    name: "Lay's Game Day Chili",
    brand: "Lays's",
    price: 2.5,
    Spicy: false,
    glutenFree: true,
    image: 1,
  },
];

console.log(menu);
export { menu };
